version: "3.8"

services:
  ##############################################################################
  ##############################################################################
  ##############################################################################
  mongo:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${DB_USER:-admin}
      MONGO_INITDB_ROOT_PASSWORD: ${DB_PASSWORD:-swordfish}
    volumes:
      - /etc/localtime:/etc/localtime:ro
      # - mongo:/etc/mongo
    networks:
      default: {}
    restart: always

  ##############################################################################
  ##############################################################################
  ##############################################################################
  # mongo-express:
  #   image: mongo-express
  #   ports:
  #     - target: 8081
  #       published: 8001
  #       protocol: tcp
  #       mode: host
  #   environment:
  #     ME_CONFIG_MONGODB_ADMINUSERNAME: ${DB_USER:-admin}
  #     ME_CONFIG_MONGODB_ADMINPASSWORD: ${DB_PASSWORD:-swordfish}
  #     ME_CONFIG_MONGODB_URL: mongodb://${DB_USER}:${DB_PASSWORD}@mongo:27017/
  #   volumes:
  #     - /etc/localtime:/etc/localtime:ro
  #   networks:
  #     default: {}
  #   restart: always

  ##############################################################################
  ##############################################################################
  ##############################################################################
  app:
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        BUILD_DATE: ${BUILD_DATE:-2021}
        VERSION: ${VERSION:-latest}

        ENV_MODE: ${ENV_MODE:-KONS}
        PROTOCOL: ${PROTOCOL:-http}
        DB_HOST: ${DB_HOST:-mongo}
        DB_PORT: ${DB_PORT:-27017}
        DB_USER: ${DB_USER:-admin}
        DB_PASSWORD: ${DB_PASSWORD:-swordfish}
    image: mvladislav/vm_api:${VERSION:-latest}
    env_file: .env
    ports:
      - target: 8000
        published: 8000
        protocol: tcp
        mode: host
    volumes:
      - /etc/localtime:/etc/localtime:ro
      # - ./app/:/app/app/
    command: uvicorn app.main:main --reload --workers 1 --host 0.0.0.0 --port 8000
      --factory
    networks:
      default: {}
    restart: always

################################################################################
################################################################################
################################################################################
networks:
  default:
    driver: ${NETWORK_MODE:-bridge}

volumes:
  mongo: {}
