version: "3.8"

services:
  ##############################################################################
  ##############################################################################
  ##############################################################################
  mongo:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${DB_USER:-admin}
      MONGO_INITDB_ROOT_PASSWORD: ${DB_PASSWORD:-swordfish}
    volumes:
      - mongo:/etc/mongo
    networks:
      default: {}
    restart: always

  ##############################################################################
  ##############################################################################
  ##############################################################################
  mongo-express:
    image: mongo-express
    ports:
      - target: 8081
        published: 8001
        protocol: tcp
        mode: host
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${DB_USER:-admin}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${DB_PASSWORD:-swordfish}
      ME_CONFIG_MONGODB_URL: mongodb://${DB_USER}:${DB_PASSWORD}@mongo:27017/
    networks:
      default: {}
    restart: always

  ##############################################################################
  ##############################################################################
  ##############################################################################
  app:
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        BUILD_DATE: ${BUILD_DATE:-2021}
        VERSION: ${VERSION:-latest}

        PROJECT_NAME: ${PROJECT_NAME:-VM-API}
        ENV_MODE: ${ENV_MODE:-KONS}
        LOGGING_LEVEL: ${LOGGING_LEVEL:-DEBUG}
        LOGGING_VERBOSE: ${LOGGING_VERBOSE:-3}
        PROTOCOL: ${PROTOCOL:-http}
        SECRET_KEY: ${SECRET_KEY}
        DB_HOST: ${DB_HOST:-mongo}
        DB_PORT: ${DB_PORT:-27017}
        DB_SCHEMA: ${DB_SCHEMA}
        DB_USER: ${DB_USER}
        DB_PASSWORD: ${DB_PASSWORD}

    image: MVladislav/vm-api:${VERSION:-latest}
    env_file: .env
    ports:
      - target: 8000
        published: 8000
        protocol: tcp
        mode: host
    # volumes:
    #   - ./app/:/vm-api/app/
    command: uvicorn app.main:main --reload --workers 1 --host 0.0.0.0 --port 8000
    networks:
      default: {}
    restart: always

################################################################################
################################################################################
################################################################################
networks:
  default:
    driver: ${NETWORK_MODE:-bridge}

volumes:
  mongo: {}
